# Generated by Django 5.0.6 on 2024-06-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('-created_at',), 'permissions': [('can_manage_gift', 'Can manage gift')], 'verbose_name': 'gift', 'verbose_name_plural': 'gifts'},
        ),
        migrations.AlterModelOptions(
            name='giftapplication',
            options={'ordering': ('created_at',), 'permissions': [('can_manage_gift_application', 'Can manage gift application')], 'verbose_name': 'gift application', 'verbose_name_plural': 'gift applications'},
        ),
    ]
