# Generated by Django 5.0.6 on 2024-06-24 17:34
from django.conf import settings
from django.db import migrations


def add_admins_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")  # noqa:
    Permission = apps.get_model("auth", "Permission")  # noqa:
    Gift = apps.get_model("items", "Gift")  # noqa:
    GiftApplication = apps.get_model("items", "GiftApplication")  # noqa:
    ContentType = apps.get_model("contenttypes", "ContentType")  # noqa:

    try:
        Group.objects.get(name=settings.ADMINS_GROUP_NAME)
    except Group.DoesNotExist:
        admins = Group.objects.create(name=settings.ADMINS_GROUP_NAME)

        gift_content_type = ContentType.objects.get_for_model(Gift)
        gift_manage_permission = Permission.objects.get(
            codename="can_manage_gift", content_type=gift_content_type
        )

        application_content_type = ContentType.objects.get_for_model(GiftApplication)
        application_manage_permission = Permission.objects.get(
            codename="can_manage_gift_application",
            content_type=application_content_type,
        )

        admins.permissions.set([gift_manage_permission, application_manage_permission])


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0010_alter_group_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("items", "0002_alter_permissions"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_admins_group),
    ]
